# Generated by Django 3.2.14 on 2022-08-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fastq_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('ILL', 'Illumina'), ('ONT', 'nanopore')], max_length=5)),
                ('file_r1', models.FileField(upload_to='files/')),
                ('file_r2', models.FileField(upload_to='files/')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('project_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
