# Generated by Django 3.2.14 on 2022-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastq_input',
            name='file_r2',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
