# Generated by Django 3.2.14 on 2022-08-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_fastq_input_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastq_input',
            name='description',
        ),
    ]
