# Generated by Django 3.2.14 on 2022-08-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_fastq_input_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('fastq_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_fastq_input', to='product.fastq_input')),
            ],
        ),
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('fastqc_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.fastq_input')),
            ],
        ),
    ]
