# Generated by Django 3.2.14 on 2022-09-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_fastqc_input_processed_fastq_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastq_input',
            name='technology',
            field=models.CharField(choices=[('illumina', 'Illumina'), ('nanopore', 'nanopore')], max_length=20),
        ),
    ]
